odalc/base/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
)

odalc/courses/urls.py
from django.conf.urls import patterns, url
from odalc.courses.views import (
    CourseDetailView,
    CourseEditView,
    CourseListingView
)
from odalc.odalc_admin.views import CourseFeedbackView
from odalc.students.views import SubmitCourseFeedbackView


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/feedback/review/$', CourseFeedbackView.as_view(), name='feedback_review'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/feedback/$', SubmitCourseFeedbackView.as_view(), name='feedback'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/edit/$', CourseEditView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^$', CourseListingView.as_view(), name='listing'),
)

odalc/students/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import password_change

from odalc.students.views import StudentRegisterView, StudentDashboardView, StudentEditView

urlpatterns = patterns('',
    url(r'^password_change/$',
        password_change,
        {
            'template_name': 'students/password_change.html',
            'post_change_redirect': 'students:dashboard'
        },
        name='password_change',
    ),
    url(r'^register/$', StudentRegisterView.as_view(), name='register'),
    url(r'^edit/$', StudentEditView.as_view(), name='edit'),
    url(r'^$', StudentDashboardView.as_view(), name='dashboard'),
)

odalc/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.views import password_change
from django.views.generic import TemplateView

from odalc.base.views import (
    AboutPageView,
    DonatePageView,
    FaqPageView,
    HomePageView,
    TalentPageView,
    WorkPageView
)

urlpatterns = patterns('',
    url(r'^admins/', include('odalc.odalc_admin.urls', namespace='admins')),
    url(r'^courses/', include('odalc.courses.urls', namespace='courses')),
    url(r'^students/', include('odalc.students.urls', namespace='students')),
    url(r'^teachers/', include('odalc.teachers.urls', namespace='teachers')),
    url(r'^users/', include('odalc.users.urls', namespace='users')),
    url(r'^about/$', AboutPageView.as_view(), name='about'),
    url(r'^donate/$', DonatePageView.as_view(), name='donate'),
    url(r'^faq/$', FaqPageView.as_view(), name='faq'),
    url(r'^work/$', WorkPageView.as_view(), name='work'),
    url(r'^talent/$', TalentPageView.as_view(), name='talent'),
    url(r'^$', HomePageView.as_view(), name='home'),
)

odalc/users/urls.py
from django.conf.urls import patterns, url

from odalc.users.views import LoginView, LogoutView

urlpatterns = patterns('',
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
)

odalc/courses/forms.py
from datetime import datetime as dt

from django import forms

from odalc.courses.models import Course


class EditCourseForm(forms.ModelForm):
    """Form class for editing Course objects. Is used by all user types, but depending on the type, the template will
    make some fields read-only. This form class uses separate fields for the course's date, start time, and end time,
    but combines those into 2 start datetime and end datetime objects when saving.
    """
    date = forms.DateField(label='Date to Teach Course', required=False)
    start_time = forms.TimeField(label='Starting Time for Course Session', required=False)
    end_time = forms.TimeField(label='Ending Time for Course Session', required=False)

    def __init__(self, *args, **kwargs):
        super(EditCourseForm, self).__init__(*args, **kwargs)
        if self.instance.start_datetime:
            self.fields['date'].initial = self.instance.start_datetime.date
            self.fields['start_time'].initial = self.instance.start_datetime.time
        if self.instance.end_datetime:
            self.fields['end_time'].initial = self.instance.end_datetime.time

    def save(self, *args, **kwargs):
        date = self.cleaned_data.get('date')
        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')
        if date and start_time:
            self.instance.start_datetime = dt.combine(date, start_time)
        if date and end_time:
            self.instance.end_datetime = dt.combine(date, end_time)
        return super(EditCourseForm, self).save(*args, **kwargs)

    class Meta:
        model = Course
        exclude = (
            'teacher',
            'students',
            'start_datetime',
            'end_datetime',
            'is_featured',
            'image_thumbnail'
        )

odalc/odalc_admin/forms.py
from django import forms

from odalc.users.forms import UserRegisterForm
from odalc.users.models import AdminUser


class AdminEditForm(forms.ModelForm):
    """Form class for editing admin user information."""
    class Meta:
        model = AdminUser
        fields = (
            'email',
            'first_name',
            'last_name'
        )


class AdminRegisterForm(UserRegisterForm):
    """Form class for adding a new admin user."""
    class Meta:
        model = AdminUser
        fields = (
            'email',
            'first_name',
            'last_name'
        )

odalc/base/views.py
import logging

from django.contrib import messages
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import TemplateView

from odalc.courses.models import Course
from odalc.users.views import UserDataMixin
from odalc.lib.payments import MissingTokenException, handle_stripe_donation

import stripe


logger = logging.getLogger(settings.ODALC_LOGGER)


class AboutPageView(UserDataMixin, TemplateView):
    """Static page for general information about BRIDGE and ODALC."""
    template_name = 'base/about.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(AboutPageView, self).dispatch(request, *args, **kwargs)


class DonatePageView(UserDataMixin, TemplateView):
    """Static page for handling donations."""
    template_name = 'base/donate.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(DonatePageView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DonatePageView, self).get_context_data(**kwargs)
        context['stripe_public_key'] = settings.STRIPE_PUBLIC_KEY
        return context

    def post(self, request, *args, **kwargs):
        # Get the credit card details submitted by the form
        token = request.POST.get('stripeToken', False)
        amount = request.POST.get('quantity', False)
        try:
            handle_stripe_donation(amount, token)
            messages.success(request, "Thank you! Your donation has been processed.")
            return redirect('donate')
        except MissingTokenException:
            messages.error(request,
                    "No payment information was included in your submission. Your card hasn't been charged")
            return redirect('donate')
        except stripe.CardError:
            # The card has been declined
            messages.error(request, "Your information was invalid or your card has been declined")
            return self.render_to_response(self.get_context_data())
        except Exception as e:
            messages.error(request,
                    "An unknown error occured. Please try again, or contact Oakland Digital if the problem persists.")
            return redirect('donate')


class FaqPageView(UserDataMixin, TemplateView):
    """ Static page for FAQ. The questions/answers are in the template file."""
    template_name = 'base/faq.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(FaqPageView, self).dispatch(request, *args, **kwargs)


class HomePageView(UserDataMixin, TemplateView):
    """Landing page for the website. Displays featured courses - if there aren't enough, upcoming and possibly past
    courses are also displayed.
    """
    NUM_COURSES_SHOWN = 3
    template_name = 'base/home.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(HomePageView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['featured_courses'] = Course.objects.get_featured(
            HomePageView.NUM_COURSES_SHOWN)
        return context


class WorkPageView(UserDataMixin, TemplateView):
    """Placeholder page for plans to make this platform open to people wanting to find partnerships for work
    opportunities - for potential employees."""
    template_name = 'base/work.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(WorkPageView, self).dispatch(request, *args, **kwargs)


class TalentPageView(UserDataMixin, TemplateView):
    """Placeholder page for plans to make this platform open to people wanting to find partnerships for work
    opportunities - for potential employees."""
    template_name = 'base/talent.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(TalentPageView, self).dispatch(request, *args, **kwargs)

odalc/courses/views.py
import datetime

from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, UpdateView

from odalc.courses.forms import EditCourseForm
from odalc.courses.models import Course
from odalc.lib.payments import (
    MissingTokenException,
    handle_stripe_course_registration,
)
from odalc.users.views import UserDataMixin


class CourseDetailView(UserDataMixin, DetailView):
    """View for displaying a single Course object."""
    model = Course
    context_object_name = 'course'
    template_name = 'courses/course.html'

    def render_to_response(self, context, **response_kwargs):
        response_kwargs.setdefault('content_type', self.content_type)
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            **response_kwargs
        )

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        course = self.get_object()
        # Redirect to the URL with the correct slug if the slug does not match
        if self.kwargs.get(self.slug_url_kwarg, None) != course.slug():
            return redirect(course, permanent=True)
        elif (
            course.is_accepted() or
            course.is_finished() or
            (self.user.is_authenticated() and (
                course.is_owner(self.user) or self.is_admin_user))
            ):
            return super(CourseDetailView, self).dispatch(request, *args, **kwargs)
        else:
            return self.deny_access()

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        course = self.get_object()
        context['stripe_public_key'] = settings.STRIPE_PUBLIC_KEY
        if self.user.is_authenticated():
            context['email'] = self.user.email
            context['in_class'] = course.is_student_in_course(self.user)
            context['submitted_feedback'] = course.is_student_feedback_submitted(self.user)
            context['is_past_start_date'] = course.is_past_start_date(datetime.datetime.now())
        context['cost_in_cents'] = course.get_cost_in_cents()
        context['course_full'] = course.is_full()
        context['course_finished'] = course.is_finished()
        context['open_seats'] = course.get_num_open_seats()
        context['is_owner'] = course.is_owner(self.user)
        return context

    def post(self, request, *args, **kwargs):
        """On the template, the 'Enroll' button is disabled if the user is signed in as a teacher or admin. Only
        unauthenticated or users authenticated as students should be sending these POST requests.
        """
        course = self.get_object()
        if request.POST.get("login-redirect"):
            # Redirect them to the login page with this page as the 'next' URL if
            # a user wants to enroll but isn't signed in
            messages.info(request, "You must be signed in to enroll in a course.")
            response = redirect('users:login')
            response['Location'] += '?next=' + reverse('courses:detail', args=[course.pk, course.slug()])
            return response
        elif course.is_full():
            messages.error(request, "This course is already full. Your card hasn't been charged")
            return redirect(course)
        elif course.is_student_in_course(self.user):
            messages.error(request, "You are already signed up for this course. Your card hasn't been charged")
            return redirect(course)
        else:
            # User is signed in as a student and has clicked "enroll"
            try:
                token = request.POST.get('stripeToken', False)
                handle_stripe_course_registration(self.user, course, token)
                course.students.add(self.user)
                course.save()
                messages.success(request, "You have successfully registered for this course!")
                return redirect(course)
            except MissingTokenException:
                messages.error(request, "No payment information was included in your submission. Your card was not charged.")
                return redirect(course)
            except stripe.CardError:
                messages.error(request, "Your information was invalid or your card has been declined.")
                return self.render_to_response(self.get_context_data())


class CourseEditView(UserDataMixin, UpdateView):
    """View for editing course information. This is used by both teacher and admin users, but certain fields are set
    to read-only in the template depending on the user type.
    """

    model = Course
    form_class = EditCourseForm
    context_object_name = 'course'
    template_name = 'courses/course_edit.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        course = self.get_object()
        if not self.user.is_authenticated():
            return redirect('/users/login?next=%s' % self.request.path)
        elif course.is_owner(self.user) or self.is_admin_user:
            return super(CourseEditView, self).dispatch(request, *args, **kwargs)
        else:
            return self.deny_access()

    def get_context_data(self, **kwargs):
        context = super(CourseEditView, self).get_context_data(**kwargs)
        context['teacher_split'] = self.get_object().get_teacher_cost_split()
        return context

    def get_success_url(self):
        messages.success(self.request, self.get_object().title + ' edited successfully')
        if self.is_teacher_user:
            return reverse('teachers:dashboard')
        elif self.is_admin_user:
            return reverse('admins:dashboard')
        else:
            # Should never happen
            return reverse('home')


class CourseListingView(UserDataMixin, ListView):
    """View for displaying the courses offered. There are three categories of courses: all courses, past courses, and
    upcoming courses.
    """
    context_object_name = 'courses'
    paginate_by = 10
    template_name = 'courses/course_listing.html'

    PARAM_TYPE = "type"
    TYPE_UPCOMING = "upcoming"
    TYPE_PAST = "past"

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(CourseListingView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = None
        courses_type = self.request.GET.get(CourseListingView.PARAM_TYPE)
        if courses_type == CourseListingView.TYPE_PAST:
            queryset =  Course.objects.get_finished()
        else:
            # Display courses coming up in the next year
            now = datetime.datetime.now()
            future = now + datetime.timedelta(days=365)
            queryset =  Course.objects.get_in_date_range(now, future)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CourseListingView, self).get_context_data(**kwargs)
        is_past = self.request.GET.get(CourseListingView.PARAM_TYPE) == CourseListingView.TYPE_PAST
        context['is_upcoming'] = not is_past
        context['is_past'] = is_past
        return context

odalc/templates/students/course_feedback_form.html
{% extends "base/base.html" %}


{% block body %}
<div class='row'>
	<h1>Feedback for {{ title }}</h1>
	<form action="{% url "courses:feedback" course.pk course.slug %}" method="POST" class='large-12 columns'>
	  {% csrf_token %}
	  <ul class='form-list'>
	    {{ form.as_ul }}
	  </ul>
	  <button id="save_feedback" class="large success radius" type="submit">Submit</button>
	</form>
</div>

{% endblock %}

odalc/templates/students/password_change.html
{% extends "users/password_change.html" %}

{% block dashboard %}{% url "students:dashboard" %}{% endblock  %}

{% block subnav %}
    {% include "students/subnav/subnav_password_change.html" %}
{% endblock %}

odalc/templates/students/register.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}Student Registration{% endblock %}

{% block body %}
<div class="white-section-no-border">
    <div class="row">
        <div class="large-5 columns">
            <h1>Student Registration</h1>
            <p class="larger">Interested in taking classes?</p>
            <p class="larger">We'll just need a few details about yourself so we can create a new account for you.</p>
        </div>
        <div class="large-5 offset-2 columns">
            <form action="{% url "students:register" %}?next={{ request.GET.next }}" method="POST">
              {% csrf_token %}

              {% for error in form.non_field_errors %}
                  <div data-alert class="alert-box alert">
                    {{ error }}
                    <a href="#" class="close">&times;</a>
                  </div>
              {% endfor %}

              {% include "base/partials/formfield.html" with field=form.email %}
              {% include "base/partials/formfield.html" with field=form.first_name %}
              {% include "base/partials/formfield.html" with field=form.last_name %}
              {% include "base/partials/formfield.html" with field=form.password1 %}
              {% include "base/partials/formfield.html" with field=form.password2 %}

              <input type="hidden" name="next" value="{{ request.GET.next }}" />
              <input class="button success right radius" type="submit" value="Register" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

odalc/templates/students/student_dashboard.html
{% extends "base/base.html" %}

{% block title %}Student Dashboard{% endblock %}

{% block nav %}
    {% include "base/partials/nav/nav_student.html" %}
{% endblock %}

{% block body %}
{% include "students/subnav/subnav_dashboard.html" %}

<div class="white-section">
<div class="row">
    <div class="large-12 columns">
        <div class="row">
            <div class="large-12 columns">
                <h2>Upcoming Courses</h2>
                {% if courses_upcoming %}
                    <table width='100%'>
                        <tr>
                            <th>Course</th>
                            <th>Teacher</th>
                            <th>Date</th>
                        </tr>
                    {% for course in courses_upcoming %}
                        <tr>
                            <td><a href="{% url "courses:detail" course.pk course.slug %}"> {{ course.title }}</a></td>
                            <td>{{ course.teacher.first_name }} {{ course.teacher.last_name }}</td>
                            <td class="right">{{ course.start_datetime|date:'D, N d Y' }} | {{ course.start_datetime|date:'P'}} - {{ course.end_datetime|date:'P' }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <h5> You aren't registered for any upcoming courses yet! </h5>
                {% endif %}
                </table>
            </div>
        </div>
        <div class="row">
            <div class="large-12 columns">
                <h2>Completed Courses</h2>
                {% if courses_taken %}
                    <table width='100%'>
                        <tr>
                            <th>Course</th>
                            <th>Teacher</th>
                            <th>Date</th>
                        </tr>
                    {% for course in courses_taken %}
                        <tr>
                            <td> <a href="{% url "courses:detail" course.pk course.slug %}"> {{ course.title }}</a> </td>
                            <td> {{ course.teacher.first_name }} {{ course.teacher.last_name }} </td>
                            <td class="right">{{ course.start_datetime|date:'D, N d Y' }} | {{ course.start_datetime|date:'P'}} - {{ course.end_datetime|date:'P' }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <h5> You haven't taken any courses yet! </h5>
                {% endif %}
                </table>
            </div>
        </div>

    </div>
</div>
</div>

{% endblock %}

odalc/templates/students/student_edit.html
{% extends "base/base.html" %}

{% load staticfiles %}

{% block nav %}
    {% include "base/partials/nav/nav_student.html" %}
{% endblock %}

{% block body %}
{% include "students/subnav/subnav_edit.html" %}

<div class="edit-user-block">
    <div class="row">
        <div class="large-7 small-centered columns">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {% for error in form.non_field_errors %}
            <div data-alert class="alert-box alert">
                {{ error }}
                <a href="#" class="close">&times;</a>
            </div>
            {% endfor %}

            {% include "base/partials/formfield.html" with field=form.email %}
            {% include "base/partials/formfield.html" with field=form.first_name %}
            {% include "base/partials/formfield.html" with field=form.last_name %}

            <input class="button radius success right" type="submit" value="Save" />
            </form>
        </div>
    </div>
</div>

{% endblock %}