odalc/base/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
)

odalc/courses/urls.py
from django.conf.urls import patterns, url
from odalc.courses.views import (
    CourseDetailView,
    CourseEditView,
    CourseListingView
)
from odalc.odalc_admin.views import CourseFeedbackView
from odalc.students.views import SubmitCourseFeedbackView


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/feedback/review/$', CourseFeedbackView.as_view(), name='feedback_review'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/feedback/$', SubmitCourseFeedbackView.as_view(), name='feedback'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/edit/$', CourseEditView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/(?P<slug>[\w-]+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^$', CourseListingView.as_view(), name='listing'),
)

odalc/students/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.views import password_change

from odalc.students.views import StudentRegisterView, StudentDashboardView, StudentEditView

urlpatterns = patterns('',
    url(r'^password_change/$',
        password_change,
        {
            'template_name': 'students/password_change.html',
            'post_change_redirect': 'students:dashboard'
        },
        name='password_change',
    ),
    url(r'^register/$', StudentRegisterView.as_view(), name='register'),
    url(r'^edit/$', StudentEditView.as_view(), name='edit'),
    url(r'^$', StudentDashboardView.as_view(), name='dashboard'),
)

odalc/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.auth.views import password_change
from django.views.generic import TemplateView

from odalc.base.views import (
    AboutPageView,
    DonatePageView,
    FaqPageView,
    HomePageView,
    TalentPageView,
    WorkPageView
)

urlpatterns = patterns('',
    url(r'^admins/', include('odalc.odalc_admin.urls', namespace='admins')),
    url(r'^courses/', include('odalc.courses.urls', namespace='courses')),
    url(r'^students/', include('odalc.students.urls', namespace='students')),
    url(r'^teachers/', include('odalc.teachers.urls', namespace='teachers')),
    url(r'^users/', include('odalc.users.urls', namespace='users')),
    url(r'^about/$', AboutPageView.as_view(), name='about'),
    url(r'^donate/$', DonatePageView.as_view(), name='donate'),
    url(r'^faq/$', FaqPageView.as_view(), name='faq'),
    url(r'^work/$', WorkPageView.as_view(), name='work'),
    url(r'^talent/$', TalentPageView.as_view(), name='talent'),
    url(r'^$', HomePageView.as_view(), name='home'),
)

odalc/users/urls.py
from django.conf.urls import patterns, url

from odalc.users.views import LoginView, LogoutView

urlpatterns = patterns('',
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
)

odalc/courses/forms.py
from datetime import datetime as dt

from django import forms

from odalc.courses.models import Course


class EditCourseForm(forms.ModelForm):
    """Form class for editing Course objects. Is used by all user types, but depending on the type, the template will
    make some fields read-only. This form class uses separate fields for the course's date, start time, and end time,
    but combines those into 2 start datetime and end datetime objects when saving.
    """
    date = forms.DateField(label='Date to Teach Course', required=False)
    start_time = forms.TimeField(label='Starting Time for Course Session', required=False)
    end_time = forms.TimeField(label='Ending Time for Course Session', required=False)

    def __init__(self, *args, **kwargs):
        super(EditCourseForm, self).__init__(*args, **kwargs)
        if self.instance.start_datetime:
            self.fields['date'].initial = self.instance.start_datetime.date
            self.fields['start_time'].initial = self.instance.start_datetime.time
        if self.instance.end_datetime:
            self.fields['end_time'].initial = self.instance.end_datetime.time

    def save(self, *args, **kwargs):
        date = self.cleaned_data.get('date')
        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')
        if date and start_time:
            self.instance.start_datetime = dt.combine(date, start_time)
        if date and end_time:
            self.instance.end_datetime = dt.combine(date, end_time)
        return super(EditCourseForm, self).save(*args, **kwargs)

    class Meta:
        model = Course
        exclude = (
            'teacher',
            'students',
            'start_datetime',
            'end_datetime',
            'is_featured',
            'image_thumbnail'
        )

odalc/odalc_admin/forms.py
from django import forms

from odalc.users.forms import UserRegisterForm
from odalc.users.models import AdminUser


class AdminEditForm(forms.ModelForm):
    """Form class for editing admin user information."""
    class Meta:
        model = AdminUser
        fields = (
            'email',
            'first_name',
            'last_name'
        )


class AdminRegisterForm(UserRegisterForm):
    """Form class for adding a new admin user."""
    class Meta:
        model = AdminUser
        fields = (
            'email',
            'first_name',
            'last_name'
        )

odalc/base/views.py
import logging

from django.contrib import messages
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import TemplateView

from odalc.courses.models import Course
from odalc.users.views import UserDataMixin
from odalc.lib.payments import MissingTokenException, handle_stripe_donation

import stripe


logger = logging.getLogger(settings.ODALC_LOGGER)


class AboutPageView(UserDataMixin, TemplateView):
    """Static page for general information about BRIDGE and ODALC."""
    template_name = 'base/about.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(AboutPageView, self).dispatch(request, *args, **kwargs)


class DonatePageView(UserDataMixin, TemplateView):
    """Static page for handling donations."""
    template_name = 'base/donate.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(DonatePageView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DonatePageView, self).get_context_data(**kwargs)
        context['stripe_public_key'] = settings.STRIPE_PUBLIC_KEY
        return context

    def post(self, request, *args, **kwargs):
        # Get the credit card details submitted by the form
        token = request.POST.get('stripeToken', False)
        amount = request.POST.get('quantity', False)
        try:
            handle_stripe_donation(amount, token)
            messages.success(request, "Thank you! Your donation has been processed.")
            return redirect('donate')
        except MissingTokenException:
            messages.error(request,
                    "No payment information was included in your submission. Your card hasn't been charged")
            return redirect('donate')
        except stripe.CardError:
            # The card has been declined
            messages.error(request, "Your information was invalid or your card has been declined")
            return self.render_to_response(self.get_context_data())
        except Exception as e:
            messages.error(request,
                    "An unknown error occured. Please try again, or contact Oakland Digital if the problem persists.")
            return redirect('donate')


class FaqPageView(UserDataMixin, TemplateView):
    """ Static page for FAQ. The questions/answers are in the template file."""
    template_name = 'base/faq.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(FaqPageView, self).dispatch(request, *args, **kwargs)


class HomePageView(UserDataMixin, TemplateView):
    """Landing page for the website. Displays featured courses - if there aren't enough, upcoming and possibly past
    courses are also displayed.
    """
    NUM_COURSES_SHOWN = 3
    template_name = 'base/home.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(HomePageView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['featured_courses'] = Course.objects.get_featured(
            HomePageView.NUM_COURSES_SHOWN)
        return context


class WorkPageView(UserDataMixin, TemplateView):
    """Placeholder page for plans to make this platform open to people wanting to find partnerships for work
    opportunities - for potential employees."""
    template_name = 'base/work.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(WorkPageView, self).dispatch(request, *args, **kwargs)


class TalentPageView(UserDataMixin, TemplateView):
    """Placeholder page for plans to make this platform open to people wanting to find partnerships for work
    opportunities - for potential employees."""
    template_name = 'base/talent.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(TalentPageView, self).dispatch(request, *args, **kwargs)

odalc/courses/views.py
import datetime

from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView, UpdateView

from odalc.courses.forms import EditCourseForm
from odalc.courses.models import Course
from odalc.lib.payments import (
    MissingTokenException,
    handle_stripe_course_registration,
)
from odalc.users.views import UserDataMixin


class CourseDetailView(UserDataMixin, DetailView):
    """View for displaying a single Course object."""
    model = Course
    context_object_name = 'course'
    template_name = 'courses/course.html'

    def render_to_response(self, context, **response_kwargs):
        response_kwargs.setdefault('content_type', self.content_type)
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            **response_kwargs
        )

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        course = self.get_object()
        # Redirect to the URL with the correct slug if the slug does not match
        if self.kwargs.get(self.slug_url_kwarg, None) != course.slug():
            return redirect(course, permanent=True)
        elif (
            course.is_accepted() or
            course.is_finished() or
            (self.user.is_authenticated() and (
                course.is_owner(self.user) or self.is_admin_user))
            ):
            return super(CourseDetailView, self).dispatch(request, *args, **kwargs)
        else:
            return self.deny_access()

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        course = self.get_object()
        context['stripe_public_key'] = settings.STRIPE_PUBLIC_KEY
        if self.user.is_authenticated():
            context['email'] = self.user.email
            context['in_class'] = course.is_student_in_course(self.user)
            context['submitted_feedback'] = course.is_student_feedback_submitted(self.user)
            context['is_past_start_date'] = course.is_past_start_date(datetime.datetime.now())
        context['cost_in_cents'] = course.get_cost_in_cents()
        context['course_full'] = course.is_full()
        context['course_finished'] = course.is_finished()
        context['open_seats'] = course.get_num_open_seats()
        context['is_owner'] = course.is_owner(self.user)
        return context

    def post(self, request, *args, **kwargs):
        """On the template, the 'Enroll' button is disabled if the user is signed in as a teacher or admin. Only
        unauthenticated or users authenticated as students should be sending these POST requests.
        """
        course = self.get_object()
        if request.POST.get("login-redirect"):
            # Redirect them to the login page with this page as the 'next' URL if
            # a user wants to enroll but isn't signed in
            messages.info(request, "You must be signed in to enroll in a course.")
            response = redirect('users:login')
            response['Location'] += '?next=' + reverse('courses:detail', args=[course.pk, course.slug()])
            return response
        elif course.is_full():
            messages.error(request, "This course is already full. Your card hasn't been charged")
            return redirect(course)
        elif course.is_student_in_course(self.user):
            messages.error(request, "You are already signed up for this course. Your card hasn't been charged")
            return redirect(course)
        else:
            # User is signed in as a student and has clicked "enroll"
            try:
                token = request.POST.get('stripeToken', False)
                handle_stripe_course_registration(self.user, course, token)
                course.students.add(self.user)
                course.save()
                messages.success(request, "You have successfully registered for this course!")
                return redirect(course)
            except MissingTokenException:
                messages.error(request, "No payment information was included in your submission. Your card was not charged.")
                return redirect(course)
            except stripe.CardError:
                messages.error(request, "Your information was invalid or your card has been declined.")
                return self.render_to_response(self.get_context_data())


class CourseEditView(UserDataMixin, UpdateView):
    """View for editing course information. This is used by both teacher and admin users, but certain fields are set
    to read-only in the template depending on the user type.
    """

    model = Course
    form_class = EditCourseForm
    context_object_name = 'course'
    template_name = 'courses/course_edit.html'

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        course = self.get_object()
        if not self.user.is_authenticated():
            return redirect('/users/login?next=%s' % self.request.path)
        elif course.is_owner(self.user) or self.is_admin_user:
            return super(CourseEditView, self).dispatch(request, *args, **kwargs)
        else:
            return self.deny_access()

    def get_context_data(self, **kwargs):
        context = super(CourseEditView, self).get_context_data(**kwargs)
        context['teacher_split'] = self.get_object().get_teacher_cost_split()
        return context

    def get_success_url(self):
        messages.success(self.request, self.get_object().title + ' edited successfully')
        if self.is_teacher_user:
            return reverse('teachers:dashboard')
        elif self.is_admin_user:
            return reverse('admins:dashboard')
        else:
            # Should never happen
            return reverse('home')


class CourseListingView(UserDataMixin, ListView):
    """View for displaying the courses offered. There are three categories of courses: all courses, past courses, and
    upcoming courses.
    """
    context_object_name = 'courses'
    paginate_by = 10
    template_name = 'courses/course_listing.html'

    PARAM_TYPE = "type"
    TYPE_UPCOMING = "upcoming"
    TYPE_PAST = "past"

    def dispatch(self, request, *args, **kwargs):
        self.set_perms(request, *args, **kwargs)
        return super(CourseListingView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = None
        courses_type = self.request.GET.get(CourseListingView.PARAM_TYPE)
        if courses_type == CourseListingView.TYPE_PAST:
            queryset =  Course.objects.get_finished()
        else:
            # Display courses coming up in the next year
            now = datetime.datetime.now()
            future = now + datetime.timedelta(days=365)
            queryset =  Course.objects.get_in_date_range(now, future)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CourseListingView, self).get_context_data(**kwargs)
        is_past = self.request.GET.get(CourseListingView.PARAM_TYPE) == CourseListingView.TYPE_PAST
        context['is_upcoming'] = not is_past
        context['is_past'] = is_past
        return context

odalc/templates/base/about.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}About Us{% endblock %}

{% block nav %}
    {% include "base/partials/nav/nav_about.html" %}
{% endblock %}

{% block body %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-535c2fec21d43eea"></script>

<div class="about-header">
    <div class="about-header-img"></div>
    <div class="about-header-overlay"></div>
    <div class="about-header-content">
        <div class="row">
            <div class="medium-8 medium-centered columns text-center">
                <h1>Our Mission</h1>
                <p>
Oakland Digital is partnering with professionals from the tech and design industry to teach practical and emerging technical skills. We believe that the opportunity to learn these skills should be available to anyone and that these skills will educate, inspire and empower under resourced communities through digital literacy.
                </p>
            </div>
        </div>
    </div>
</div>
<div class="about-content">
    <div class="row" data-equalizer>
        <div class="medium-6 columns about-col" data-equalizer-watch>
            <h2>For Students</h2>
            <p>
Use your experience and skills to make an immediate impact. Whether you're a creative director at an ad agency or a software engineer at a tech company, mentor students with direct, hands-on training to help them use technology thoughtfully, responsibly and professionally.
            </p>
            <a href="{% url "students:register" %}">Register to be a student &raquo;</a>
        </div>
        <div class="medium-6 columns about-col" data-equalizer-watch>
            <h2>For Teachers</h2>
            <p>
Oakland Digital is an on a mission to bridge the digital literacy and opportunity gap. We’re a not-for-profit with the goal to build the next pipeline of young creatives of color by providing real-world opportunities to work with under resourced small business’.
            </p>
            <a href="{% url "teachers:register" %}">Apply to be a teacher &raquo;</a>
        </div>
    </div>
</div>

<div id="about-bottom-image">
</div>

<div class="about-bottom-section">
    <div class="row">
        <div class="small-12 medium-9 end columns">
            <h2>About Oakland Digital</h2>
            <p>
Oakland Digital is an on a mission to bridge the digital literacy and opportunity gap. We’re a not-for-profit with the goal to build the next pipeline of young creatives of color by providing real-world opportunities to work with under resourced small business’.
            </p>
        </div>
    </div>
    <div class="row">
        <div class = "medium-7 columns">
            <ul class="inline-list">
                <li>
                    <div>
                    <a href="https://twitter.com/ODALC" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @ODALC</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </div>
                </li>
                <li>
                    <div class="fb-follow" data-href="https://www.facebook.com/odalc" data-colorscheme="light" data-layout="button_count" data-show-faces="true"></div>
                </li>
                <li>
                    <div>
                        <div class="g-follow" data-annotation="bubble" data-height="24" data-href="https://plus.google.com/100653295456413757353" data-rel="publisher"></div>
                        <script type="text/javascript">
                          (function() {
                            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                            po.src = 'https://apis.google.com/js/platform.js';
                            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                          })();
                        </script>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

odalc/templates/base/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} | BRIDGE - A Platform By Oakland Digital</title>

    <link rel="shortcut icon" href="{% static "img/base/odalc_16px.ico" %}" type="image/x-icon"/>
    <link rel="icon" href="{% static "img/base/ODALC-16px.png" %}" type="image/png"/>
    <link rel="apple-touch-icon" type="image/x-icon" href="{% static "img/base/ODALC-57px.png" %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{% static "img/base/ODALC-72px.png" %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="{% static "img/base/ODALC-117px.png" %}">

    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.2/css/toastr.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" type="text/css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.6/slick.css" />
    <link rel="stylesheet" href="{% static "css/main.css" %}" />
    {% block css %}{% endblock %}
    {% block javascript-head %}{% endblock %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
  </head>
  <body>
    {% block nav %}
        {% include "base/partials/nav/nav.html" %}
    {% endblock %}

    <div class="main-wrap">
    {% block body %}
    {% endblock %}
    </div>

    {% block footer %}
        {% include "base/partials/footer.html" %}
    {% endblock %}

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.4.5/js/foundation.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.4.5/js/foundation/foundation.slider.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.4.5/js/foundation/foundation.magellan.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.2/js/toastr.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.3/fastclick.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.6/slick.min.js"></script>

    <script src="{% static "js/base/jquery.confirmon.min.js" %}"></script>
    <script src="{% static "js/base/app.js" %}"></script>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
            toastr.{{ message.tags }}('{{ message }}')
        </script>
        {% endfor %}
    </ul>
    {% endif %}

    <script>
      $(document).foundation();
    </script>
    {% block javascripts %}
    {% endblock %}
  </body>
</html>

odalc/templates/base/home.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}Home{% endblock %}

{% block nav %}
{% include "base/partials/nav/nav_home.html" %}
{% endblock %}

{% block body %}
<div id="main-splash">
    <div class="main-splash-img">
        <div class="splash-image" style="background-image: url({% static "img/base/home/home_1.jpg" %});"></div>
        <div class="splash-image" style="background-image: url({% static "img/base/home/home_2.jpg" %});"></div>
        <div class="splash-image" style="background-image: url({% static "img/base/home/home_3.jpg" %});"></div>
        <div class="splash-image" style="background-image: url({% static "img/base/home/home_6.jpg" %});"></div>
        <div class="splash-image" style="background-image: url({% static "img/base/home/home_4.jpg" %});"></div>
        <div class="splash-image" style="background-image: url({% static "img/base/home/home_5.jpg" %});"></div>
    </div>
    <div class="main-splash-overlay"></div>
    <div class="main-splash-content">
        <div class="row">
            <div class="medium-9 medium-centered columns">
                <h1>Learn from your community's leading tech & design professionals</h1>
            </div>
        </div>
        <div class="row">
            <div class="small-12 small-centered columns button-set">
                {% if not user.is_authenticated %}
                <a href="{% url "courses:listing" %}" class="landing-button">Take Courses</a>
                <a href="{% url "teachers:register" %}" class="landing-button">Teach Courses</a>
                <a href="{% url "work" %}" class="landing-button">Help Businesses</a>
                <a href="{% url "talent" %}" class="landing-button">Hire Talent</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="light-grey-section">
    <!-- Upcoming courses title/description -->
    <div class="row course-items-description">
        <div class="large-12 columns">
            <h3>Featured Courses</h3>
        </div>
    </div>

    <!-- Upcoming courses items -->

    <div class="row course-items">
        {% for course in featured_courses %}
        <div class="course-box">
            <a href="{% url "courses:detail" course.pk course.slug %}">
                <div class="top-shelf">
                    <div class="title-wrap">
                        <h4>{{ course.title }}</h4>
                    </div>
                    <img src="{{ course.image_thumbnail.url }}"></img>
                </div>
                <div class="bottom-shelf">
                    <h4>With {{ course.teacher.first_name }} {{ course.teacher.last_name }}</h4>
                    <h4> {{ course.start_datetime|date:'l, F jS' }}</h4>
                </div>
            </a>
        </div>
        {% endfor %}
        <a class="right" href="{% url "courses:listing" %}">Browse all courses &raquo;</a>
    </div>
</div>

<div class="home-about-section">
    <div class="row">
        <div class="medium-7 columns">
            <h3><strong>What is BRIDGE?</strong></h3>
            <p>
            BRIDGE is an education platform that partners with professionals from the tech and design industry to offer courses that teach practical technical skills. We envision a future where under resourced communities have access to professional opportunities. BRIDGE aims to empower people with digital literacy education that will improve their lives and the communities they live in.

            Whether it's learning how to manage your business' brand through social media or code your first website, empower yourself to harness the the digital tools to succeed in the 21st century.
            </p>
            <a href="{% url "about" %}">Learn more &raquo;</a>
        </div>
        <div class="medium-5 columns text-center">
            <img src="{% static "img/base/bridge-logo-circle.png" %}"/>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
<script src="{% static "js/base/home.js" %}"></script>
{% endblock %}

odalc/templates/base/talent.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}Hire Local Talent{% endblock %}

{% block nav %}
{% include "base/partials/nav/nav_home.html" %}
{% endblock %}

{% block body %}
<div class="talent-header">
    <div class="talent-header-img"></div>
    <div class="talent-header-overlay"></div>
    <div class="talent-header-content">
        <div class="row">
            <div class="medium-8 medium-centered columns text-center">
                <h1>Hire Local Talent</h1>
                <p>
                Launching 2015
                </p>
            </div>
        </div>
    </div>
</div>
<div class="talent-content">
    <div class="row">
        <div class="medium-8 medium-centered columns">
            <p>
            Professional graphic design and creative services while helping our community. Request a demo with <a href="mailto:shaun@odalc.org">shaun@odalc.org</a>
            </p>
        </div>
    </div>
</div>

{% endblock %}

odalc/templates/base/work.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}Work{% endblock %}

{% block nav %}
{% include "base/partials/nav/nav_home.html" %}
{% endblock %}

{% block body %}
<div class="work-header">
    <div class="work-header-img"></div>
    <div class="work-header-overlay"></div>
    <div class="work-header-content">
        <div class="row">
            <div class="medium-8 medium-centered columns text-center">
                <h1>Find Work Opportunities</h1>
                <p>
                Coming Soon
                </p>
            </div>
        </div>
    </div>
</div>
<div class="work-content">
    <div class="row" data-equalizer>
        <div class="medium-8 medium-centered columns">
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum mi vel ornare dignissim. Mauris hendrerit tellus quis libero accumsan, a viverra turpis pellentesque. Sed aliquam at nibh id condimentum. Integer eget erat vestibulum, consequat eros eget, pulvinar sapien. Maecenas iaculis dictum mauris, in tempor augue aliquam sit amet. Curabitur odio nulla, tincidunt vitae nulla at, porttitor convallis justo. Sed sit amet dui in orci efficitur iaculis ac nec dui.
            </p>
        </div>
    </div>
</div>

{% endblock %}